package Structs

type MakePayment struct {
	StoreId string `json:"store_id"`
	StorePasswd string `json:"store_passwd"`
	TotalAmount string `json:"total_amount"`
	Currency	string `json:"currency"`
	TranId string `json:"tran_id"`
	ProductCategory string `json:"product_category"`
	SuccessUrl string `json:"success_url"`
	FailUrl string `json:"fail_url"`
	CancelUrl string `json:"cancel_url"`
	ipnUrl string `json:"ipn_url"`
	MultiCardName string `json:"multi_card_name"`
	AllowedBin string `json:"allowed_bin"`
	EmiOption string `json:"emi_option"`
	EmiMaxInstOption string `json:"emi_max_inst_option"`
	EmiSelectedInst string `json:"emi_selected_inst"`
	EmiAllowOnly string `json:"emi_allow_only"`
	CusName string `json:"cus_name"`
	CusEmail string `json:"cus_email"`
	CusAdd1 string `json:"cus_add_1"`
	CusAdd2 string `json:"cus_add_2"`
	CusCity string `json:"cus_city"`
	CusState string `json:"cus_state"`
	CusPostcode string `json:"cus_postcode"`
	CusCountry string `json:"cus_country"`
	CusPhone string `json:"cus_phone"`
	CusFax string `json:"cus_fax"`
	ShippingMethod string `json:"shipping_method"`
	NumOfItem string `json:"num_of_item"`
	ShipName string `json:"ship_name"`
	ShipAdd1 string `json:"ship_add_1"`
	ShipAdd2 string `json:"ship_add_2"`
	ShipCity string `json:"ship_city"`
	ShipState string `json:"ship_state"`
	ShipPostcode string `json:"ship_postcode"`
	ShipCountry string `json:"ship_country"`
	ProductName string `json:"product_name"`
	ProductProfile string `json:"product_profile"`
	HoursTillDeparture string `json:"hours_till_departure"`
	flightType string `json:"flight_type"`
	Pnr string `json:"pnr"`
	journeyFromTo string `json:"journey_from_to"`
	thirdPartyBooking string `json:"third_party_booking"`
	HotelName string `json:"hotel_name"`
	LengthOfStay string `json:"length_of_stay"`
	CheckInTime string `json:"check_in_time"`
	HotelCity string `json:"hotel_city"`
	ProductType string `json:"product_type"`
	TopupNumber string `json:"topup_number"`
	CountryTopup string `json:"country_topup"`
	Cart string `json:"cart"`
	ProductAmount string `json:"product_amount"`
	Vat string `json:"vat"`
	DiscountAmount string `json:"discount_amount"`
	ConvenienceFee string `json:"convenience_fee"`
	ValueA string `json:"value_a"`
	ValueB string `json:"value_b"`
	ValueC string `json:"value_c"`
	ValueD string `json:"value_d"`
}